config/routes.rb
CalcentralTaskPlanner::Application.routes.draw do
  devise_for :users

  resources :tasks do
    resources :subtasks
  end
  root to: 'tasks#index'

end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
  attr_accessible :description, :is_done, :task
  belongs_to :task
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :due, :status, :title, :course, :kind, :release, :user_id
  belongs_to :user
  has_many :subtasks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
  					:first_name, :last_name
  # attr_accessible :title, :body
  has_many :tasks
  
  def full_name
  	first_name + " " + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
  # GET /subtasks
  # GET /subtasks.json
  def index
    task = Task.find(params[:task_id])
    @subtasks = task.subtasks

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subtasks }
    end
  end

  # GET /subtasks/1
  # GET /subtasks/1.json
  def show
    task = Task.find(params[:task_id])
    @subtask = task.subtasks.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subtask }
    end
  end

  # GET /subtasks/new
  # GET /subtasks/new.json
  def new
    task = Task.find(params[:task_id])
    @subtask = task.subtasks.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subtask }
    end
  end

  # GET /subtasks/1/edit
  def edit
    task = Task.find(params[:task_id])
    @subtask = task.subtasks.find(params[:id])
  end

  # POST /subtasks
  # POST /subtasks.json
  def create
    task = Task.find(params[:task_id])
    @subtask = task.subtasks.create(params[:subtask])

    respond_to do |format|
      if @subtask.save
        format.html { redirect_to [@subtask.task, @subtask], notice: 'Subtask was successfully created.' }
        format.json { render json: @subtask, status: :created, location: @subtask }
      else
        format.html { render action: "new" }
        format.json { render json: @subtask.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subtasks/1
  # PUT /subtasks/1.json
  def update
    task = Task.find(params[:task_id])
    @subtask = task.subtasks.find(params[:id])

    respond_to do |format|
      if @subtask.update_attributes(params[:subtask])
        format.html { redirect_to [@subtask.task, @subtask], notice: 'Subtask was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subtask.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subtasks/1
  # DELETE /subtasks/1.json
  def destroy
    task = Task.find(params[:task_id])
    @subtask = task.subtasks.find(params[:id])
    @subtask.destroy

    respond_to do |format|
      format.html { redirect_to task_path(task) }
      format.json { head :no_content }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subtasks_helper.rb
module SubtasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!-- !!! 5
%html
  %head
    %title CalCentral Task Planner
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %h1.title CalCentral Task Planner
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]
      %p{:class=>"notice"}= notice
      %p{:class=>"alert"}= alert
      = yield
 -->

<!DOCTYPE html>
<html>
<head>
  <title>CalCentral Task Planner</title>
  <%= stylesheet_link_tag 'application'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags%>
</head>
<body>
  <% if current_user != nil %>
    <p>
    <%= link_to current_user.full_name, edit_user_registration_path %> |
    <%= link_to 'Sign Out', destroy_user_session_path,  method: :delete %>
    </p>
  <% else %>
    <p><%=link_to 'Sign In', new_user_session_path %></p>
  <% end %>
  <h1 class="title">CalCentral Task Planner</h1>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</body>
</html>

app/views/subtasks/_form.html.erb
<%= form_for([@subtask.task, @subtask]) do |f| %>
  <% if @subtask.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subtask.errors.count, "error") %> prohibited this subtask from being saved:</h2>

      <ul>
      <% @subtask.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :is_done %><br />
    <%= f.check_box :is_done %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subtasks/edit.html.erb
<h1>Editing subtask</h1>

<%= render 'form' %>

<%= link_to 'Show', [@subtask.task, @subtask] %> |
<%= link_to 'Back', task_subtasks_path %>

app/views/subtasks/index.html.erb
<h1>Listing subtasks</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Is done</th>
    <th>Task</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subtasks.each do |subtask| %>
  <tr>
    <td><%= subtask.description %></td>
    <td><%= subtask.is_done %></td>
    <td><%= subtask.task %></td>
    <td><%= link_to 'Show', [subtask.task, subtask] %></td>
    <td><%= link_to 'Edit', edit_task_subtask_path(subtask.task, subtask) %></td>
    <td><%= link_to 'Destroy', [subtask.task, subtask], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subtask', new_task_subtask_path(params[:task_id]) %>
<%= link_to 'Back to Task', task_path(params[:task_id])%>

app/views/subtasks/new.html.erb
<h1>New subtask</h1>

<%= render 'form' %>

<%= link_to 'Back', task_subtasks_path(@subtask.task) %>
<%= link_to 'Back To Task', task_path(@subtask.task) %> <br>

app/views/subtasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @subtask.description %>
</p>

<p>
  <b>Is done:</b>
  <%= @subtask.is_done %>
</p>

<p>
  <b>Task:</b>
  <%= @subtask.task %>
</p>


<%= link_to 'Edit', edit_task_subtask_path(@subtask.task, @subtask) %> |
<%= link_to 'Back', task_subtasks_path(@subtask.task) %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :due %><br />
    <%= f.datetime_select :due %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :course %><br />
    <%= f.text_field :course %>
  </div>
  <div class="field">
    <%= f.label :kind %><br />
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :release %><br />
    <%= f.datetime_select :release %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing subtask</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>

<table id="tasks">
  <tr>
    <th>Task Title</th>
    <th>Course</th>
    <th>Kind</th>
    <th>Release Date</th>
    <th>Due Date</th>
    <th>Status</th>
    <th>Owner</th>
  </tr>
<% @tasks.each do |task| %>
  <tr>
    <td><%= link_to task.title, task_path(task) %></td>
    <td><%= task.course %></td>
    <td><%= task.kind %></td>
    <td><%= task.release.strftime("%B %d, %Y") %></td>
    <td><%= task.due.strftime("%B %d, %Y")%></td>
    <td><%= task.status%></td>
    <td><%= task.user.full_name%></td>
  </tr>
<% end %>
</table>

<%= link_to 'Add new task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>
<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<h1>Details of <%= @task.title%></h1>

<p id="notice"><%= notice %></p>
<ul>
  <li>Title: <%= @task.title %></li>
  <li>Course: <%= @task.course %></li>
  <li>Kind: <%= @task.kind %></li>
  <li>Relase Date: <%= @task.release %></li>
  <li>Due Date: <%= @task.due %></li>
  <li>Status: <%= @task.status %></li>
</ul>

<%= link_to 'Edit Task', edit_task_path(@task) %> <%= button_to 'Delete', task_path(@task), :method => :delete, :confirm => 'Are you sure?'%>
<h1>Listing <%= link_to 'subtasks', task_subtasks_path(@task)%></h1>

<table>
  <tr>
    <th>Is done</th>
    <th>Description</th>
    <!-- <th>Task</th> -->
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @task.subtasks.each do |subtask| %>
  <tr>
    <td><%= subtask.is_done %></td>
    <td><%= subtask.description %></td>
    <!-- <td><%= subtask.task %></td> -->
    <td><%= link_to 'Show', [subtask.task, subtask] %></td>
    <td><%= link_to 'Edit', edit_task_subtask_path(subtask.task, subtask) %></td>
    <td><%= link_to 'Destroy', [subtask.task, subtask], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br>

<%= link_to 'New Subtask', new_task_subtask_path(@task.id) %> <br>
<%= link_to 'Back to task list', tasks_path %><br>